### ISSUE TITLE
I was able to complete installation, but how about any guidance how to use this? 

### ISSUE THREAD

**Issue by danny3b** [mirko-pagliai/thumbs#6]

**Comment by mirko-pagliai** [comment]
Hello @danny3b .
This is just a little unpretentious code.

Simple, you have to use the `Thumb` helper and its method.

Try something like this:

    echo $this->Thumb->resize('https://i.ytimg.com/vi/3v5Q_dPQUYo/maxresdefault.jpg', ['width' => 100]);

Or this:

    echo $this->Thumb->square('https://i.ytimg.com/vi/3v5Q_dPQUYo/maxresdefault.jpg', ['side' => 100]);

These methods work like the `img()` method provided by the `HtmlHelper`. You can pass `height` or `width` options for the `resize()` method and the `side` option for the `square()` method.

They can also handle remote img.

**Comment by mirko-pagliai** [comment]
@danny3b let me know if you can use the plugin. I did not believe could be of interest to other people and I would be happy if it were so. I have just a little time, I write a little documentation

**Comment by danny3b** [comment]
Unfortunately, I didn't succeed. Maybe I've installed it wrong, because I had to do that manually, and maybe I missed something. When I do that with composer my app fall apart. Little documentation could help, although I'll try again with clean version of CakePHP.

**Comment by mirko-pagliai** [comment]
Sorry @danny3b tell me what I can do to help you

**Comment by mirko-pagliai** [comment]
the `README` file explains how to create thumbnails (https://github.com/mirko-pagliai/thumbs/commit/e0f060d65b3af890c3476c8ee9d90e3e5bbeb859 and https://github.com/mirko-pagliai/thumbs/commit/8b62e0ce0af15b33e84ecff040d39cf2dbbce9a9)
